[2025-06-23T00:34:16.028+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-23T00:34:16.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.analize manual__2025-06-23T00:33:24.960659+00:00 [queued]>
[2025-06-23T00:34:16.078+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.analize manual__2025-06-23T00:33:24.960659+00:00 [queued]>
[2025-06-23T00:34:16.079+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-23T00:34:16.116+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): analize> on 2025-06-23 00:33:24.960659+00:00
[2025-06-23T00:34:16.130+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'analize', 'manual__2025-06-23T00:33:24.960659+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp31_aumw6']
[2025-06-23T00:34:16.134+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask analize
[2025-06-23T00:34:16.139+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=520) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-23T00:34:16.140+0000] {standard_task_runner.py:63} INFO - Started process 529 to run task
[2025-06-23T00:34:16.230+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.analize manual__2025-06-23T00:33:24.960659+00:00 [running]> on host c254c61929aa
[2025-06-23T00:34:16.419+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='analize' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T00:33:24.960659+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T00:33:24.960659+00:00'
[2025-06-23T00:34:16.422+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-23T00:34:16.595+0000] {hive.py:475} INFO - USE `default`
[2025-06-23T00:34:16.688+0000] {hive.py:475} INFO -  
        CREATE OR REPLACE VIEW sales_by_mon AS
        SELECT
            CAST(date_format(CAST(o.datetime AS timestamp), 'yyyy') AS INT) AS year,
            CAST(date_format(CAST(o.datetime AS timestamp), 'MM') AS INT) AS month,
            SUM(ol.price) AS total_sales
        FROM `order` o
        JOIN order_line ol ON o.order_id = ol.order_id
        GROUP BY 
            CAST(date_format(CAST(o.datetime AS timestamp), 'yyyy') AS INT),
            CAST(date_format(CAST(o.datetime AS timestamp), 'MM') AS INT)
    
[2025-06-23T00:34:18.603+0000] {hive.py:475} INFO -  
        CREATE OR REPLACE VIEW sales_by_product AS
        SELECT 
            name AS product_name,
            SUM(price) AS total_sales
        FROM product_sales
        GROUP BY name
    
[2025-06-23T00:34:18.755+0000] {hive.py:475} INFO -  
        CREATE OR REPLACE VIEW reservations_by_date AS
        SELECT 
            TO_DATE(datetime) AS reservation_date,
            COUNT(*) AS num_reservations
        FROM reservation
        GROUP BY TO_DATE(datetime)
    
[2025-06-23T00:34:18.935+0000] {hive.py:475} INFO -  
        CREATE OR REPLACE VIEW top_selling_products AS
        WITH ranked_products AS (
            SELECT 
                restaurant_id,
                product_id,
                name,
                SUM(price) AS total_sales,
                ROW_NUMBER() OVER (PARTITION BY restaurant_id ORDER BY SUM(price) DESC) AS rank
            FROM product_sales
            GROUP BY restaurant_id, product_id, name
        )
        SELECT 
            restaurant_id,
            name,
            total_sales
        FROM ranked_products
        WHERE rank = 1
    
[2025-06-23T00:34:19.027+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-23T00:34:19.028+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/olap_cubes.py", line 42, in create_views
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.12/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException [Error 10004]: Line 11:21 Invalid table alias or column reference 'restaurant_id': (possible column names are: product_id, name, menu_id, order_id, price):17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 11:21 Invalid table alias or column reference 'restaurant_id': (possible column names are: product_id, name, menu_id, order_id, price):35:19", 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genAllExprNodeDesc:SemanticAnalyzer.java:11620', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11568', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11536', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11514', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genGroupByPlanMapGroupByOperator:SemanticAnalyzer.java:5202', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genGroupByPlanMapAggrNoSkew:SemanticAnalyzer.java:6307', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genBodyPlan:SemanticAnalyzer.java:9629', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10549', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10414', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10441', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10427', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genOPTree:SemanticAnalyzer.java:11125', 'org.apache.hadoop.hive.ql.parse.CalcitePlanner:genOPTree:CalcitePlanner.java:481', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:11138', 'org.apache.hadoop.hive.ql.parse.CalcitePlanner:analyzeInternal:CalcitePlanner.java:286', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=10004, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10004]: Line 11:21 Invalid table alias or column reference 'restaurant_id': (possible column names are: product_id, name, menu_id, order_id, price)"), operationHandle=None)
[2025-06-23T00:34:19.054+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=analize, run_id=manual__2025-06-23T00:33:24.960659+00:00, execution_date=20250623T003324, start_date=20250623T003416, end_date=20250623T003419
[2025-06-23T00:34:19.098+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 169 for task analize (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException [Error 10004]: Line 11:21 Invalid table alias or column reference 'restaurant_id': (possible column names are: product_id, name, menu_id, order_id, price):17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 11:21 Invalid table alias or column reference 'restaurant_id': (possible column names are: product_id, name, menu_id, order_id, price):35:19", 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genAllExprNodeDesc:SemanticAnalyzer.java:11620', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11568', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11536', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11514', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genGroupByPlanMapGroupByOperator:SemanticAnalyzer.java:5202', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genGroupByPlanMapAggrNoSkew:SemanticAnalyzer.java:6307', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genBodyPlan:SemanticAnalyzer.java:9629', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10549', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10414', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10441', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10427', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genOPTree:SemanticAnalyzer.java:11125', 'org.apache.hadoop.hive.ql.parse.CalcitePlanner:genOPTree:CalcitePlanner.java:481', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:11138', 'org.apache.hadoop.hive.ql.parse.CalcitePlanner:analyzeInternal:CalcitePlanner.java:286', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=10004, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10004]: Line 11:21 Invalid table alias or column reference 'restaurant_id': (possible column names are: product_id, name, menu_id, order_id, price)"), operationHandle=None); 529)
[2025-06-23T00:34:19.128+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-23T00:34:19.154+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-23T00:34:19.156+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
