[2025-06-21T21:47:16.810+0000] {processor.py:161} INFO - Started process (PID=26) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:16.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:47:16.825+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:16.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:16.923+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:16.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:47:16.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:17.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.973 seconds
[2025-06-21T21:47:49.500+0000] {processor.py:161} INFO - Started process (PID=27) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:49.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:47:49.529+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:49.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:49.865+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:49.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:47:49.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:50.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.176 seconds
[2025-06-21T21:48:22.110+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:22.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:48:22.115+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:22.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:22.134+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:22.129+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:48:22.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:22.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.108 seconds
[2025-06-21T21:48:52.765+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:52.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:48:52.780+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:52.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:52.874+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:52.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:48:52.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:53.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.311 seconds
[2025-06-21T21:49:23.165+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:23.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:49:23.173+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:23.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:23.193+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:23.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:49:23.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:23.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.202 seconds
[2025-06-21T21:49:54.528+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:54.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:49:54.534+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:54.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:54.554+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:54.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:49:54.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:54.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.104 seconds
[2025-06-21T21:50:24.842+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:24.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:50:24.847+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:24.846+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:24.873+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:24.867+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:50:24.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:24.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.118 seconds
[2025-06-21T21:50:55.156+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:55.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:50:55.163+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:55.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:55.183+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:55.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:50:55.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:55.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.099 seconds
[2025-06-21T21:51:25.395+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:25.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:51:25.399+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:25.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:25.419+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:25.414+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:51:25.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:25.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-06-21T21:51:56.200+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:56.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:51:56.206+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:56.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:56.225+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:56.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:51:56.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:56.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.079 seconds
[2025-06-21T21:52:26.843+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:26.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:52:26.849+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:26.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:26.869+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:26.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:52:26.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:26.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.101 seconds
[2025-06-21T21:52:58.028+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:58.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:52:58.034+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:58.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:58.052+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:58.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:52:58.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:58.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.068 seconds
[2025-06-21T21:53:28.772+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:28.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:53:28.776+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:28.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:28.798+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:28.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:53:28.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:28.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.072 seconds
[2025-06-21T21:53:59.353+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:59.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:53:59.357+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:59.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:59.379+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:59.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:53:59.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:59.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-06-21T21:54:29.893+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:54:29.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:54:29.896+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:54:29.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:54:29.910+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:54:29.907+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:54:29.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:54:29.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.082 seconds
[2025-06-21T21:55:00.462+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:00.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:55:00.465+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:00.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:00.481+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:00.478+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:55:00.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:00.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.071 seconds
[2025-06-21T21:55:31.133+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:31.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:55:31.135+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:31.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:31.148+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:31.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:55:31.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:31.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.056 seconds
[2025-06-21T21:56:01.739+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:01.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:56:01.741+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:01.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:01.755+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:01.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:56:01.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:01.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.058 seconds
[2025-06-21T21:56:32.341+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:32.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:56:32.344+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:32.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:32.357+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:32.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:56:32.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:32.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.051 seconds
[2025-06-21T21:57:02.915+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:02.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:57:02.918+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:02.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:02.937+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:02.933+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:57:02.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:02.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.067 seconds
[2025-06-21T21:57:33.553+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:33.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:57:33.556+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:33.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:33.571+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:33.568+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:57:33.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:33.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.057 seconds
[2025-06-21T21:58:04.199+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:04.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:58:04.201+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:04.201+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:04.213+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:04.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:58:04.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:04.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.055 seconds
[2025-06-21T21:58:34.874+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:34.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:58:34.877+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:34.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:34.891+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:34.889+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:58:34.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:34.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.067 seconds
[2025-06-21T21:59:05.457+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:05.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:59:05.461+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:05.460+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:05.481+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:05.479+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:59:05.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:05.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.076 seconds
[2025-06-21T21:59:36.055+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:36.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:59:36.058+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:36.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:36.073+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:36.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:59:36.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:36.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.062 seconds
[2025-06-21T22:00:06.422+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:06.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:00:06.424+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:06.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:06.439+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:06.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:00:06.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:06.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.061 seconds
[2025-06-21T22:00:36.753+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:36.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:00:36.757+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:36.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:36.775+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:36.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:00:36.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:36.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:01:07.044+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:07.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:01:07.046+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:07.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:07.070+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:07.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:01:07.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:07.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.108 seconds
[2025-06-21T22:01:37.525+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:37.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:01:37.528+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:37.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:37.553+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:37.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:01:37.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:37.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:02:07.866+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:07.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:02:07.870+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:07.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:07.892+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:07.888+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:02:07.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:07.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.081 seconds
[2025-06-21T22:02:38.226+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:38.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:02:38.231+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:38.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:38.249+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:38.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:02:38.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:38.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.097 seconds
[2025-06-21T22:03:08.544+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:08.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:03:08.549+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:08.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:08.566+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:08.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:03:08.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:08.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2025-06-21T22:03:38.870+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:38.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:03:38.877+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:38.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:38.902+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:38.898+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:03:38.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:38.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
