[2025-06-21T21:47:16.810+0000] {processor.py:161} INFO - Started process (PID=26) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:16.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:47:16.825+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:16.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:16.923+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:16.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:47:16.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:17.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.973 seconds
[2025-06-21T21:47:49.500+0000] {processor.py:161} INFO - Started process (PID=27) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:49.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:47:49.529+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:49.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:49.865+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:47:49.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:47:49.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:47:50.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.176 seconds
[2025-06-21T21:48:22.110+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:22.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:48:22.115+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:22.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:22.134+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:22.129+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:48:22.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:22.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.108 seconds
[2025-06-21T21:48:52.765+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:52.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:48:52.780+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:52.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:52.874+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:48:52.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:48:52.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:48:53.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.311 seconds
[2025-06-21T21:49:23.165+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:23.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:49:23.173+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:23.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:23.193+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:23.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:49:23.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:23.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.202 seconds
[2025-06-21T21:49:54.528+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:54.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:49:54.534+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:54.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:54.554+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:49:54.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:49:54.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:49:54.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.104 seconds
[2025-06-21T21:50:24.842+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:24.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:50:24.847+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:24.846+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:24.873+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:24.867+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:50:24.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:24.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.118 seconds
[2025-06-21T21:50:55.156+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:55.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:50:55.163+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:55.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:55.183+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:50:55.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:50:55.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:50:55.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.099 seconds
[2025-06-21T21:51:25.395+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:25.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:51:25.399+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:25.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:25.419+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:25.414+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:51:25.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:25.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-06-21T21:51:56.200+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:56.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:51:56.206+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:56.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:56.225+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:51:56.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:51:56.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:51:56.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.079 seconds
[2025-06-21T21:52:26.843+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:26.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:52:26.849+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:26.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:26.869+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:26.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:52:26.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:26.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.101 seconds
[2025-06-21T21:52:58.028+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:58.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:52:58.034+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:58.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:58.052+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:52:58.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:52:58.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:52:58.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.068 seconds
[2025-06-21T21:53:28.772+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:28.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:53:28.776+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:28.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:28.798+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:28.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:53:28.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:28.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.072 seconds
[2025-06-21T21:53:59.353+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:59.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:53:59.357+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:59.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:59.379+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:53:59.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:53:59.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:53:59.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-06-21T21:54:29.893+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:54:29.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:54:29.896+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:54:29.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:54:29.910+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:54:29.907+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:54:29.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:54:29.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.082 seconds
[2025-06-21T21:55:00.462+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:00.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:55:00.465+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:00.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:00.481+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:00.478+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:55:00.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:00.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.071 seconds
[2025-06-21T21:55:31.133+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:31.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:55:31.135+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:31.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:31.148+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:55:31.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:55:31.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:55:31.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.056 seconds
[2025-06-21T21:56:01.739+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:01.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:56:01.741+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:01.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:01.755+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:01.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:56:01.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:01.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.058 seconds
[2025-06-21T21:56:32.341+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:32.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:56:32.344+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:32.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:32.357+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:56:32.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:56:32.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:56:32.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.051 seconds
[2025-06-21T21:57:02.915+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:02.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:57:02.918+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:02.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:02.937+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:02.933+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:57:02.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:02.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.067 seconds
[2025-06-21T21:57:33.553+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:33.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:57:33.556+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:33.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:33.571+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:57:33.568+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:57:33.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:57:33.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.057 seconds
[2025-06-21T21:58:04.199+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:04.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:58:04.201+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:04.201+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:04.213+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:04.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:58:04.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:04.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.055 seconds
[2025-06-21T21:58:34.874+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:34.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:58:34.877+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:34.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:34.891+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:58:34.889+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:58:34.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:58:34.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.067 seconds
[2025-06-21T21:59:05.457+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:05.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:59:05.461+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:05.460+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:05.481+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:05.479+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:59:05.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:05.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.076 seconds
[2025-06-21T21:59:36.055+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:36.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T21:59:36.058+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:36.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:36.073+0000] {logging_mixin.py:188} INFO - [2025-06-21T21:59:36.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T21:59:36.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T21:59:36.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.062 seconds
[2025-06-21T22:00:06.422+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:06.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:00:06.424+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:06.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:06.439+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:06.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:00:06.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:06.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.061 seconds
[2025-06-21T22:00:36.753+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:36.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:00:36.757+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:36.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:36.775+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:00:36.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:00:36.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:00:36.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:01:07.044+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:07.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:01:07.046+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:07.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:07.070+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:07.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:01:07.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:07.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.108 seconds
[2025-06-21T22:01:37.525+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:37.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:01:37.528+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:37.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:37.553+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:01:37.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:01:37.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:01:37.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:02:07.866+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:07.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:02:07.870+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:07.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:07.892+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:07.888+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:02:07.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:07.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.081 seconds
[2025-06-21T22:02:38.226+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:38.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:02:38.231+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:38.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:38.249+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:02:38.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:02:38.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:02:38.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.097 seconds
[2025-06-21T22:03:08.544+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:08.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:03:08.549+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:08.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:08.566+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:08.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:03:08.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:08.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2025-06-21T22:03:38.870+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:38.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:03:38.877+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:38.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:38.902+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:03:38.898+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:03:38.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:03:38.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:04:09.332+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:04:09.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:04:09.335+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:04:09.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:04:09.348+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:04:09.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:04:09.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:04:09.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.092 seconds
[2025-06-21T22:04:39.751+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:04:39.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:04:39.756+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:04:39.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:04:39.780+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:04:39.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:04:39.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:04:39.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.076 seconds
[2025-06-21T22:05:10.013+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:05:10.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:05:10.017+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:05:10.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:05:10.032+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:05:10.029+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:05:10.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:05:10.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.061 seconds
[2025-06-21T22:05:40.312+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:05:40.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:05:40.315+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:05:40.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:05:40.326+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:05:40.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:05:40.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:05:40.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.054 seconds
[2025-06-21T22:06:10.526+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:06:10.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:06:10.529+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:06:10.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:06:10.543+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:06:10.540+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:06:10.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:06:10.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.058 seconds
[2025-06-21T22:06:40.832+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:06:40.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:06:40.835+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:06:40.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:06:40.847+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:06:40.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:06:40.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:06:40.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.054 seconds
[2025-06-21T22:07:11.120+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:07:11.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:07:11.124+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:07:11.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:07:11.137+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:07:11.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:07:11.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:07:11.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.061 seconds
[2025-06-21T22:07:41.321+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:07:41.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:07:41.325+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:07:41.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:07:41.345+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:07:41.340+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:07:41.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:07:41.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.120 seconds
[2025-06-21T22:08:11.697+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:08:11.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:08:11.701+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:08:11.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:08:11.726+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:08:11.719+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:08:11.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:08:11.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.118 seconds
[2025-06-21T22:08:42.068+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:08:42.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:08:42.080+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:08:42.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:08:42.093+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:08:42.090+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:08:42.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:08:42.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.073 seconds
[2025-06-21T22:09:12.337+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:09:12.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:09:12.340+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:09:12.340+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:09:12.362+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:09:12.358+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:09:12.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:09:12.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.101 seconds
[2025-06-21T22:09:42.864+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:09:42.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:09:42.871+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:09:42.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:09:42.898+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:09:42.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:09:42.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:09:42.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.149 seconds
[2025-06-21T22:10:13.318+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:10:13.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:10:13.326+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:10:13.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:10:13.351+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:10:13.346+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:10:13.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:10:13.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.142 seconds
[2025-06-21T22:10:43.662+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:10:43.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:10:43.670+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:10:43.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:10:43.693+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:10:43.688+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:10:43.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:10:43.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.123 seconds
[2025-06-21T22:11:14.050+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:11:14.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:11:14.057+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:11:14.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:11:14.077+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:11:14.073+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:11:14.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:11:14.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.080 seconds
[2025-06-21T22:11:44.370+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:11:44.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:11:44.374+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:11:44.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:11:44.388+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:11:44.385+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:11:44.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:11:44.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.074 seconds
[2025-06-21T22:12:14.615+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:12:14.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:12:14.620+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:12:14.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:12:14.639+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:12:14.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:12:14.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:12:14.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.084 seconds
[2025-06-21T22:12:44.847+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:12:44.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:12:44.851+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:12:44.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:12:44.872+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:12:44.868+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:12:44.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:12:44.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.087 seconds
[2025-06-21T22:13:15.182+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:13:15.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:13:15.189+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:13:15.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:13:15.209+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:13:15.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:13:15.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:13:15.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.105 seconds
[2025-06-21T22:13:45.605+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:13:45.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:13:45.609+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:13:45.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:13:45.627+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:13:45.623+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:13:45.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:13:45.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.077 seconds
[2025-06-21T22:14:15.931+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:14:15.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:14:15.937+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:14:15.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:14:15.961+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:14:15.956+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:14:15.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:14:16.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.090 seconds
[2025-06-21T22:14:46.345+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:14:46.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:14:46.356+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:14:46.355+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:14:46.391+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:14:46.384+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:14:46.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:14:46.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.155 seconds
[2025-06-21T22:15:16.708+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:15:16.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:15:16.713+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:15:16.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:15:16.735+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:15:16.730+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:15:16.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:15:16.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.116 seconds
[2025-06-21T22:15:47.130+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:15:47.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:15:47.138+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:15:47.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:15:47.155+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:15:47.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:15:47.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:15:47.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2025-06-21T22:16:17.448+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:16:17.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:16:17.452+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:16:17.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:16:17.470+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:16:17.466+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:16:17.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:16:17.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.102 seconds
[2025-06-21T22:16:47.843+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:16:47.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:16:47.847+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:16:47.846+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:16:47.867+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:16:47.862+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:16:47.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:16:47.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.090 seconds
[2025-06-21T22:17:18.238+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:17:18.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:17:18.243+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:17:18.243+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:17:18.263+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:17:18.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:17:18.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:17:18.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.139 seconds
[2025-06-21T22:17:48.642+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:17:48.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:17:48.650+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:17:48.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:17:48.674+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:17:48.669+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:17:48.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:17:48.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.085 seconds
[2025-06-21T22:18:18.938+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:18:18.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:18:18.943+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:18:18.942+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:18:18.965+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:18:18.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:18:18.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:18:19.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.112 seconds
[2025-06-21T22:18:49.364+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:18:49.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:18:49.368+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:18:49.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:18:49.384+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:18:49.380+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:18:49.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:18:49.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.072 seconds
[2025-06-21T22:19:19.654+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:19:19.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:19:19.660+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:19:19.659+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:19:19.684+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:19:19.679+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:19:19.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:19:19.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.099 seconds
[2025-06-21T22:19:50.078+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:19:50.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:19:50.089+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:19:50.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:19:50.120+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:19:50.113+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:19:50.123+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:19:50.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.154 seconds
[2025-06-21T22:20:20.481+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:20:20.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:20:20.488+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:20:20.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:20:20.512+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:20:20.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:20:20.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:20:20.594+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.125 seconds
[2025-06-21T22:20:50.874+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:20:50.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:20:50.879+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:20:50.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:20:50.898+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:20:50.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:20:50.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:20:50.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.079 seconds
[2025-06-21T22:21:21.167+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:21:21.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:21:21.171+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:21:21.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:21:21.187+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:21:21.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:21:21.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:21:21.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.081 seconds
[2025-06-21T22:21:51.355+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:21:51.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:21:51.359+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:21:51.359+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:21:51.381+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:21:51.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:21:51.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:21:51.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.083 seconds
[2025-06-21T22:22:21.677+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:22:21.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:22:21.684+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:22:21.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:22:21.704+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:22:21.700+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:22:21.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:22:21.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.098 seconds
[2025-06-21T22:22:52.109+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:22:52.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:22:52.125+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:22:52.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:22:52.156+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:22:52.146+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:22:52.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:22:52.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.160 seconds
[2025-06-21T22:23:22.457+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:23:22.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:23:22.469+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:23:22.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:23:22.496+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:23:22.490+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:23:22.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:23:22.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.137 seconds
[2025-06-21T22:23:52.739+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:23:52.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:23:52.745+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:23:52.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:23:52.763+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:23:52.759+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:23:52.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:23:52.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-06-21T22:24:23.141+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:24:23.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:24:23.148+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:24:23.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:24:23.169+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:24:23.164+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:24:23.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:24:23.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.109 seconds
[2025-06-21T22:24:53.555+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:24:53.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:24:53.559+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:24:53.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:24:53.580+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:24:53.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:24:53.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:24:53.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.080 seconds
[2025-06-21T22:25:23.857+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:25:23.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:25:23.866+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:25:23.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:25:23.887+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:25:23.883+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:25:23.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:25:23.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2025-06-21T22:25:54.270+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:25:54.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:25:54.275+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:25:54.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:25:54.293+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:25:54.289+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:25:54.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:25:54.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:26:24.580+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:26:24.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:26:24.585+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:26:24.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:26:24.605+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:26:24.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:26:24.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:26:24.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.089 seconds
[2025-06-21T22:26:54.994+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:26:54.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:26:55.000+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:26:54.999+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:26:55.020+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:26:55.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:26:55.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:26:55.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.127 seconds
[2025-06-21T22:27:25.393+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:27:25.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:27:25.401+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:27:25.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:27:25.423+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:27:25.418+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:27:25.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:27:25.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.103 seconds
[2025-06-21T22:27:55.811+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:27:55.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:27:55.815+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:27:55.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:27:55.833+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:27:55.829+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:27:55.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:27:55.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.090 seconds
[2025-06-21T22:28:26.205+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:28:26.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:28:26.210+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:28:26.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:28:26.230+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:28:26.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:28:26.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:28:26.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.083 seconds
[2025-06-21T22:28:56.503+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:28:56.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:28:56.506+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:28:56.506+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:28:56.524+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:28:56.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:28:56.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:28:56.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2025-06-21T22:29:26.821+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:29:26.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:29:26.826+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:29:26.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:29:26.849+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:29:26.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:29:26.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:29:26.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2025-06-21T22:29:57.194+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:29:57.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:29:57.199+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:29:57.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:29:57.218+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:29:57.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:29:57.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:29:57.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.074 seconds
[2025-06-21T22:30:27.489+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:30:27.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:30:27.493+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:30:27.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:30:27.510+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:30:27.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:30:27.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:30:27.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.068 seconds
[2025-06-21T22:30:57.794+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:30:57.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:30:57.797+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:30:57.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:30:57.814+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:30:57.810+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:30:57.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:30:57.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.073 seconds
[2025-06-21T22:31:28.029+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:31:28.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:31:28.032+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:31:28.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:31:28.051+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:31:28.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:31:28.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:31:28.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.072 seconds
[2025-06-21T22:31:58.322+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:31:58.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:31:58.326+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:31:58.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:31:58.344+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:31:58.340+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:31:58.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:31:58.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.076 seconds
[2025-06-21T22:32:28.501+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:32:28.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:32:28.505+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:32:28.505+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:32:28.523+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:32:28.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:32:28.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:32:28.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.096 seconds
[2025-06-21T22:32:58.911+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:32:58.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:32:58.914+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:32:58.914+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:32:58.934+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:32:58.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:32:58.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:32:58.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.080 seconds
[2025-06-21T22:33:29.225+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:33:29.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:33:29.228+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:33:29.228+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:33:29.243+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:33:29.240+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:33:29.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:33:29.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.072 seconds
[2025-06-21T22:33:59.510+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:33:59.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:33:59.514+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:33:59.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:33:59.533+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:33:59.528+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:33:59.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:33:59.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2025-06-21T22:34:29.814+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:34:29.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:34:29.817+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:34:29.817+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:34:29.836+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:34:29.832+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:34:29.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:34:29.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2025-06-21T22:35:00.105+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:35:00.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:35:00.109+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:35:00.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:35:00.131+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:35:00.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:35:00.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:35:00.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2025-06-21T22:35:30.445+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:35:30.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:35:30.449+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:35:30.448+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:35:30.474+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:35:30.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:35:30.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:35:30.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-06-21T22:36:00.838+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:36:00.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:36:00.843+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:36:00.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:36:00.866+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:36:00.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:36:00.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:36:00.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.105 seconds
[2025-06-21T22:36:31.242+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:36:31.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:36:31.246+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:36:31.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:36:31.297+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:36:31.292+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:36:31.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:36:31.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.123 seconds
[2025-06-21T22:37:01.471+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:37:01.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:37:01.475+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:37:01.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:37:01.496+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:37:01.491+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:37:01.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:37:01.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2025-06-21T22:37:31.875+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:37:31.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:37:31.879+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:37:31.879+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:37:31.899+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:37:31.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:37:31.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:37:31.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.080 seconds
[2025-06-21T22:38:02.196+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:38:02.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:38:02.231+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:38:02.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:38:02.256+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:38:02.250+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:38:02.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:38:02.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.137 seconds
[2025-06-21T22:38:32.598+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:38:32.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:38:32.603+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:38:32.602+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:38:32.623+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:38:32.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:38:32.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:38:32.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.107 seconds
[2025-06-21T22:39:03.065+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:39:03.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:39:03.071+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:39:03.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:39:03.096+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:39:03.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:39:03.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:39:03.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.118 seconds
[2025-06-21T22:42:43.852+0000] {processor.py:161} INFO - Started process (PID=25) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:42:44.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:42:44.140+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:42:44.139+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:42:44.180+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:42:44.171+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:42:44.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:42:44.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.491 seconds
[2025-06-21T22:43:15.826+0000] {processor.py:161} INFO - Started process (PID=26) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:43:15.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:43:15.871+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:43:15.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:43:15.908+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:43:15.901+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:43:15.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:43:16.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.267 seconds
[2025-06-21T22:43:47.077+0000] {processor.py:161} INFO - Started process (PID=27) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:43:47.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:43:47.115+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:43:47.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:43:47.137+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:43:47.132+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:43:47.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:43:47.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.136 seconds
[2025-06-21T22:44:17.817+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:44:17.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:44:17.822+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:44:17.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:44:17.896+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:44:17.870+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:44:17.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:44:19.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.220 seconds
[2025-06-21T22:44:49.199+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:44:49.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:44:49.209+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:44:49.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:44:49.236+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:44:49.231+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:44:49.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:44:49.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.110 seconds
[2025-06-21T22:47:20.112+0000] {processor.py:161} INFO - Started process (PID=24) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:47:20.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:47:20.131+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:47:20.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:47:20.256+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:47:20.219+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:47:20.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:47:20.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.458 seconds
[2025-06-21T22:47:50.795+0000] {processor.py:161} INFO - Started process (PID=25) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:47:50.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:47:50.808+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:47:50.803+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:47:50.829+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:47:50.825+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:47:50.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:47:50.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.119 seconds
[2025-06-21T22:48:21.486+0000] {processor.py:161} INFO - Started process (PID=26) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:48:21.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:48:21.490+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:48:21.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:48:21.506+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:48:21.503+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:48:21.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:48:21.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.081 seconds
[2025-06-21T22:48:51.712+0000] {processor.py:161} INFO - Started process (PID=27) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:48:51.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:48:51.716+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:48:51.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:48:51.731+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:48:51.728+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:48:51.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:48:51.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.096 seconds
[2025-06-21T22:49:21.960+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:49:21.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:49:21.964+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:49:21.963+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:49:21.976+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:49:21.973+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:49:21.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:49:22.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.090 seconds
[2025-06-21T22:49:52.182+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:49:52.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:49:52.186+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:49:52.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:49:52.199+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:49:52.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:49:52.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:49:52.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.066 seconds
[2025-06-21T22:50:22.531+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:50:22.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:50:22.539+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:50:22.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:50:22.562+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:50:22.557+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:50:22.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:50:22.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.112 seconds
[2025-06-21T22:50:53.520+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:50:53.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:50:53.530+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:50:53.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:50:53.561+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:50:53.552+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:50:53.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:50:53.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.145 seconds
[2025-06-21T22:51:26.796+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:51:26.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:51:26.856+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:51:26.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:51:26.998+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:51:26.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:51:27.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:51:27.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.812 seconds
[2025-06-21T22:51:57.877+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:51:57.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:51:57.884+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:51:57.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:51:57.911+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:51:57.906+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:51:57.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:51:57.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.105 seconds
[2025-06-21T22:52:28.735+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:52:28.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:52:28.740+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:52:28.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:52:28.767+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:52:28.761+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:52:28.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:52:28.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.121 seconds
[2025-06-21T22:52:59.686+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:52:59.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:52:59.695+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:52:59.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:52:59.714+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:52:59.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:52:59.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:52:59.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.086 seconds
[2025-06-21T22:53:30.738+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:53:30.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:53:30.744+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:53:30.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:53:30.771+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:53:30.765+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:53:30.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:53:30.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.134 seconds
[2025-06-21T22:54:01.945+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:54:01.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:54:01.952+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:54:01.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:54:01.984+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:54:01.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:54:01.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:54:02.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.115 seconds
[2025-06-21T22:54:33.020+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:54:33.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:54:33.027+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:54:33.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:54:33.059+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:54:33.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:54:33.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:54:33.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.129 seconds
[2025-06-21T22:55:03.256+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:55:03.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:55:03.263+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:55:03.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:55:03.288+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:55:03.282+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:55:03.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:55:03.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.129 seconds
[2025-06-21T22:55:34.074+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:55:34.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:55:34.079+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:55:34.078+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:55:34.099+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:55:34.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:55:34.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:55:34.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.097 seconds
[2025-06-21T22:56:04.597+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:56:04.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:56:04.606+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:56:04.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:56:04.635+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:56:04.630+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:56:04.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:56:04.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.138 seconds
[2025-06-21T22:56:35.518+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:56:35.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:56:35.533+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:56:35.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:56:35.564+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:56:35.554+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:56:35.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:56:35.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.159 seconds
[2025-06-21T22:57:05.924+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:57:05.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:57:05.930+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:57:05.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:57:05.962+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:57:05.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:57:05.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:57:06.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.135 seconds
[2025-06-21T22:57:37.224+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:57:37.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:57:37.230+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:57:37.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:57:37.264+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:57:37.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:57:37.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:57:37.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.143 seconds
[2025-06-21T22:58:08.030+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:58:08.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:58:08.039+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:58:08.038+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:58:08.102+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:58:08.087+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:58:08.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:58:08.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.167 seconds
[2025-06-21T22:58:38.516+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_dag.py
[2025-06-21T22:58:38.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-06-21T22:58:38.525+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:58:38.524+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:58:38.558+0000] {logging_mixin.py:188} INFO - [2025-06-21T22:58:38.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from scripts.extract_postgres import extract_from_postgres
ModuleNotFoundError: No module named 'scripts.extract_postgres'
[2025-06-21T22:58:38.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-06-21T22:58:38.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.150 seconds
